config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('printery.users.urls', namespace='users')),
    url(r'^', include('printery.articles.urls', namespace='articles')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

printery/articles/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url, include
from rest_framework import routers

from .views import ArticleListView, UserArticleListView, ArticleAPIView

router = routers.DefaultRouter()
router.register(r'api/articles', ArticleAPIView, base_name='api_article')

urlpatterns = [
    url(r'^', include(router.urls)),

    url(
        regex=r'^articles/$',
        view=ArticleListView.as_view(),
        name='article_list'
    ),
    url(
        regex=r'^articles/user/$',
        view=UserArticleListView.as_view(),
        name='user_article_list'
    ),
]

printery/articles/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from printery.common.mixins import UUIDModel, DateTimeStampedModel

User = get_user_model()


@python_2_unicode_compatible
class Article(UUIDModel, DateTimeStampedModel):
    NEW = 'new'
    REVIEW = 'review'
    APPROVED = 'approved'

    STATUSES = (
        (NEW, _('New')),
        (REVIEW, _('Review')),
        (APPROVED, _('Approved')),
    )
    status = models.CharField(max_length=255,
                              verbose_name=_('Status'),
                              choices=STATUSES,
                              default=NEW)
    article_url = models.URLField(verbose_name=_('Article Url'),
                                  help_text=_('Url should point to google docs.'),
                                  blank=True, null=True)
    title = models.CharField(max_length=255,
                             verbose_name=_('Title'))
    editor = models.ForeignKey(User,
                               related_name='edited_articles',
                               verbose_name=_('Editor'),
                               null=True)
    writer = models.ForeignKey(User,
                               related_name='written_articles',
                               verbose_name=_('Writer'),
                               null=True)

    class Meta:
        ordering = ('create_at',)

    def __str__(self):
        return self.title

    def clean(self):
        if not self.article_url and (self.status in [self.REVIEW, self.APPROVED]):
            raise ValidationError(_('Article can\'t be approved with empty article url.'))

printery/articles/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from braces.views import LoginRequiredMixin
from django.views.generic import ListView
from rest_framework.permissions import IsAuthenticated
from rest_framework.viewsets import ModelViewSet
from printery.common.mixins import QueryMixin
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from .models import Article
from .serializers import ArticleSerializer


class ArticleListView(LoginRequiredMixin, QueryMixin, ListView):
    model = Article
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_writer:
            return queryset.filter(status=Article.NEW, writer__isnull=True)
        elif self.request.user.is_editor:
            return queryset.filter(status=Article.REVIEW, editor__isnull=True)
        else:
            return queryset.none()


class UserArticleListView(LoginRequiredMixin, QueryMixin, ListView):
    model = Article
    template_name = 'articles/user_article_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()

        if self.request.user.is_writer:
            return queryset.filter(writer=self.request.user).order_by('-status')
        elif self.request.user.is_editor:
            return queryset.filter(editor=self.request.user).order_by('-status')
        else:
            return queryset.none()


class ArticleAPIView(ModelViewSet):
    permission_classes = (IsAuthenticated,)
    queryset = Article.objects.all()
    serializer_class = ArticleSerializer
    http_method_names = ['get', 'patch', 'head', 'options', 'trace']

    def perform_update(self, serializer):
        messages.add_message(self.request, messages.SUCCESS, _('Article was successfully updated.'))
        serializer.save()

printery/articles/templates/articles/article_list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <div class="row">
    <div class="col-lg-12">
      <div class="row">
        <div class="col-lg-12">
          <table class="table">
            <thead>
            <tr>
              <th scope="col">{% trans 'Title' %}</th>
              <th scope="col">{% trans 'Action' %}</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
              <tr>
                <td>{{ object.title }}</td>
                <td>
                {% if user.is_writer %}
                  <i class="fa fa-hand-paper assign_writer"
                     data-url="{% url 'articles:api_article-detail' pk=object.pk %}"
                     data-title="{{ object.title }}"
                     data-modal-title="{% trans 'Confirmation' %}"
                     data-message="{% blocktrans %} Are you sure that you want to assign '{{ object }}' to yourself? {% endblocktrans %}"
                     data-writer="{{ user.pk }}"
                     data-button-title="{% trans 'Submit' %}"
                     data-input-name="writer"
                     data-input-value="{{ user.pk }}"
                     data-input-type="hidden"
                     title="{% trans 'Assign to yourself' %}"
                  ></i>
                {% elif user.is_editor %}
                  <i class="fa fa-hand-paper assign_writer"
                     data-url="{% url 'articles:api_article-detail' pk=object.pk %}"
                     data-title="{{ object.title }}"
                     data-modal-title="{% trans 'Confirmation' %}"
                     data-message="{% blocktrans %} Are you sure that you want to assign '{{ object }}' to yourself? {% endblocktrans %}"
                     data-writer="{{ user.pk }}"
                     data-button-title="{% trans 'Submit' %}"
                     data-input-name="editor"
                     data-input-value="{{ user.pk }}"
                     data-input-type="hidden"
                     title="{% trans 'Assign to yourself' %}"
                  ></i>
                {% endif %}
                </td>
              </tr>
               {% empty %}
              <tr>
              <td colspan="2">{% trans "There aren't articles yet." %}</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="row">
          <div class="col-lg-12 text-center">
            <nav class="navigation">
              <ul class="pagination">
                {% if page_obj.has_previous %}
                  <li class="page-item">
                    <a class="page-link"
                       href="{% url 'articles:article_list' %}?page={{ page_obj.previous_page_number }}&{{ query_param }}"
                       aria-label="Previous">
                      <span aria-hidden="true">&laquo;</span>
                    </a>
                  </li>
                {% endif %}

                {% for page_number in paginator.page_range %}

                  {% if page_obj.number|add:"-5" == page_number and not forloop.first %}
                    <li class="page-item disabled">
                                        <span>
                                            ...
                                        </span>
                    </li>
                  {% endif %}
                  {% if page_obj.number|add:"-5" < page_number and page_number < page_obj.number|add:"5" or forloop.first or forloop.last %}
                    {% if page_number == page_obj.number %}
                      <li class="page-item active">
                                            <span class="page-link">
                                                {{ page_number }}
                                            </span>
                      </li>
                    {% else %}
                      <li class="page-item">
                        <a class="page-link"
                           href="{% url 'articles:article_list' %}?page={{ page_number }}&{{ query_param }}">
                          {{ page_number }}
                        </a>
                      </li>
                    {% endif %}
                  {% endif %}

                  {% if page_obj.number|add:"5" == page_number and not forloop.last %}
                    <li class="page-item disabled">
                                        <span>
                                            ...
                                        </span>
                    </li>
                  {% endif %}

                {% endfor %}

                {% if page_obj.has_next %}
                  <li class="page-item">
                    <a class="page-link"
                       href="{% url 'articles:article_list' %}?page={{ page_obj.next_page_number }}&{{ query_param }}"
                       aria-label="Next">
                      <span aria-hidden="true">&raquo;</span>
                    </a>
                  </li>
                {% endif %}


              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>


  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
       aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">{% trans 'Confirm Assignment' %}</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="" id="modal-form" method="PATCH" class="form">

            <div class="form-group">
              <input type="url" class="form-control input" placeholder="{% trans 'Enter Article Url' %}" required>
            </div>
          </form>
          <p class="message"></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'Close' %}</button>
          <button type="submit" form="modal-form" class="btn btn-primary">{% trans 'Assign' %}</button>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

printery/articles/templates/articles/user_article_list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
  <div class="row">
    <div class="col-lg-12">
      <div class="row">
        <div class="col-lg-12">
          <table class="table">
            <thead>
            <tr>
              <th scope="col">{% trans 'Title' %}</th>
              <th scope="col">{% trans 'Article Url' %}</th>
              <th scope="col">{% trans 'Status' %}</th>
              <th scope="col">{% trans 'Action' %}</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
              <tr>
                <td>{{ object.title }}</td>
                <td>
                  {% if object.article_url %}
                    <a href="{{ object.article_url }}">{{ object.article_url }}</a>

                  {% endif %}
                </td>
                <td>{{ object.get_status_display }}</td>
                <td>
                  {% if user.is_writer %}
                    {% if object.status != 'approved' %}
                      <i class="fa fa-edit edit_article"
                         data-url="{% url 'articles:api_article-detail' pk=object.pk %}"
                         data-title="{{ object.title }}"
                         data-modal-title="{% trans 'Update Article' %}"
                         data-message=""
                         data-button-title="{% trans 'Update' %}"
                         data-input-name="article_url"
                         data-input-value="{{ object.article_url|default_if_none:"" }}"
                         data-input-type="url"
                         title="{% trans 'Edit Article' %}"
                      ></i>
                      {% if object.article_url %}
                        <i class="fa fa-share-square edit_article"
                           data-url="{% url 'articles:api_article-detail' pk=object.pk %}"
                           data-title="{{ object.title }}"
                           data-modal-title="{% trans 'Confirmation' %}"
                           data-message="{% blocktrans %} Are you sure that you want to submit article '{{ object }}' to review? {% endblocktrans %}"
                           data-button-title="{% trans 'Submit' %}"
                           data-input-name="status"
                           data-input-value="review"
                           data-input-type="hidden"
                           title="{% trans 'Submit to review' %}"
                        ></i>
                      {% endif %}
                    {% endif %}
                  {% elif user.is_editor %}
                    {% if object.status != 'approved' %}
                      <i class="fa fa-thumbs-up edit_article"
                         data-url="{% url 'articles:api_article-detail' pk=object.pk %}"
                         data-title="{{ object.title }}"
                         data-modal-title="{% trans 'Confirmation' %}"
                         data-message="{% blocktrans %} Are you sure that you want to approve article '{{ object }}'? {% endblocktrans %}"
                         data-button-title="{% trans 'Submit' %}"
                         data-input-name="status"
                         data-input-value="approved"
                         data-input-type="hidden"
                         title="{% trans 'Approve' %}"
                      ></i>
                    {% endif %}
                  {% endif %}
                </td>
              </tr>
            {% empty %}
              <tr>
                <td colspan="4">{% trans "There aren't articles yet." %}</td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>
        <div class="row">
          <div class="col-lg-12 text-center">
            <nav class="navigation">
              <ul class="pagination">
                {% if page_obj.has_previous %}
                  <li class="page-item">
                    <a class="page-link"
                       href="{% url 'articles:article_list' %}?page={{ page_obj.previous_page_number }}&{{ query_param }}"
                       aria-label="Previous">
                      <span aria-hidden="true">&laquo;</span>
                    </a>
                  </li>
                {% endif %}

                {% for page_number in paginator.page_range %}

                  {% if page_obj.number|add:"-5" == page_number and not forloop.first %}
                    <li class="page-item disabled">
                                        <span>
                                            ...
                                        </span>
                    </li>
                  {% endif %}
                  {% if page_obj.number|add:"-5" < page_number and page_number < page_obj.number|add:"5" or forloop.first or forloop.last %}
                    {% if page_number == page_obj.number %}
                      <li class="page-item active">
                                            <span class="page-link">
                                                {{ page_number }}
                                            </span>
                      </li>
                    {% else %}
                      <li class="page-item">
                        <a class="page-link"
                           href="{% url 'articles:article_list' %}?page={{ page_number }}&{{ query_param }}">
                          {{ page_number }}
                        </a>
                      </li>
                    {% endif %}
                  {% endif %}

                  {% if page_obj.number|add:"5" == page_number and not forloop.last %}
                    <li class="page-item disabled">
                                        <span>
                                            ...
                                        </span>
                    </li>
                  {% endif %}

                {% endfor %}

                {% if page_obj.has_next %}
                  <li class="page-item">
                    <a class="page-link"
                       href="{% url 'articles:article_list' %}?page={{ page_obj.next_page_number }}&{{ query_param }}"
                       aria-label="Next">
                      <span aria-hidden="true">&raquo;</span>
                    </a>
                  </li>
                {% endif %}


              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>


  <!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
       aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">{% trans 'Confirm Assignment' %}</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <form action="" id="modal-form" method="PATCH" class="form">

            <div class="form-group">
              <input type="url" class="form-control input" placeholder="{% trans 'Enter Article Url' %}" required>
            </div>
          </form>
          <p class="message"></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">{% trans 'Close' %}</button>
          <button type="submit" form="modal-form" class="btn btn-primary submit">{% trans 'Assign' %}</button>
        </div>
      </div>
    </div>
  </div>
{% endblock %}