config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('printery.users.urls', namespace='users')),
    url(r'^', include('printery.articles.urls', namespace='articles')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

printery/articles/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url, include
from rest_framework import routers

from .views import ArticleListView, UserArticleListView, ArticleAPIView

router = routers.DefaultRouter()
router.register(r'api/articles', ArticleAPIView, base_name='api_article')

urlpatterns = [
    url(r'^', include(router.urls)),

    url(
        regex=r'^articles/$',
        view=ArticleListView.as_view(),
        name='article_list'
    ),
    url(
        regex=r'^articles/user/$',
        view=UserArticleListView.as_view(),
        name='user_article_list'
    ),
]

printery/common/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

printery/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

printery/articles/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _

from printery.common.mixins import UUIDModel, DateTimeStampedModel

User = get_user_model()


@python_2_unicode_compatible
class Article(UUIDModel, DateTimeStampedModel):
    NEW = 'new'
    REVIEW = 'review'
    APPROVED = 'approved'

    STATUSES = (
        (NEW, _('New')),
        (REVIEW, _('Review')),
        (APPROVED, _('Approved')),
    )
    status = models.CharField(max_length=255,
                              verbose_name=_('Status'),
                              choices=STATUSES,
                              default=NEW)
    article_url = models.URLField(verbose_name=_('Article Url'),
                                  help_text=_('Url should point to google docs.'),
                                  blank=True, null=True)
    title = models.CharField(max_length=255,
                             verbose_name=_('Title'))
    editor = models.ForeignKey(User,
                               related_name='edited_articles',
                               verbose_name=_('Editor'),
                               null=True)
    writer = models.ForeignKey(User,
                               related_name='written_articles',
                               verbose_name=_('Writer'),
                               null=True)

    class Meta:
        ordering = ('create_at',)

    def __str__(self):
        return self.title

    def clean(self):
        if not self.article_url and (self.status in [self.REVIEW, self.APPROVED]):
            raise ValidationError(_('Article can\'t be approved with empty article url.'))

printery/common/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

printery/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):
    WRITER = 'writer'
    EDITOR = 'editor'
    ROLES = (
        (WRITER, _('Writer')),
        (EDITOR, _('Editor')),
    )

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    role = models.CharField(max_length=255,
                            choices=ROLES,
                            default=WRITER,
                            verbose_name=_('Role'),
                            null=True,
                            blank=True)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

    @property
    def is_writer(self):
        return self.role == self.WRITER

    @property
    def is_editor(self):
        return self.role == self.EDITOR

printery/users/forms.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from allauth.account.forms import SignupForm
from django import forms
from django.contrib.auth import get_user_model
from django.forms import widgets
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class CustomSignupForm(SignupForm):
    role = forms.CharField(widget=forms.Select(choices=User.ROLES))

printery/articles/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from braces.views import LoginRequiredMixin
from django.views.generic import ListView
from rest_framework.permissions import IsAuthenticated
from rest_framework.viewsets import ModelViewSet
from printery.common.mixins import QueryMixin
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _
from .models import Article
from .serializers import ArticleSerializer


class ArticleListView(LoginRequiredMixin, QueryMixin, ListView):
    model = Article
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_writer:
            return queryset.filter(status=Article.NEW, writer__isnull=True)
        elif self.request.user.is_editor:
            return queryset.filter(status=Article.REVIEW, editor__isnull=True)
        else:
            return queryset.none()


class UserArticleListView(LoginRequiredMixin, QueryMixin, ListView):
    model = Article
    template_name = 'articles/user_article_list.html'

    def get_queryset(self):
        queryset = super().get_queryset()

        if self.request.user.is_writer:
            return queryset.filter(writer=self.request.user).order_by('-status')
        elif self.request.user.is_editor:
            return queryset.filter(editor=self.request.user).order_by('-status')
        else:
            return queryset.none()


class ArticleAPIView(ModelViewSet):
    permission_classes = (IsAuthenticated,)
    queryset = Article.objects.all()
    serializer_class = ArticleSerializer
    http_method_names = ['get', 'patch', 'head', 'options', 'trace']

    def perform_update(self, serializer):
        messages.add_message(self.request, messages.SUCCESS, _('Article was successfully updated.'))
        serializer.save()

printery/common/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

printery/users/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

printery/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

printery/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}printery{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
      <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
            integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
      <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css"
            crossorigin="anonymous">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    {% endblock %}

  </head>

  <body>

  <div id="loader">
    <div class='uil-ring-css' style='transform:scale(0.6);'>
      <div></div>
    </div>
  </div>

  {% if messages %}
    <ul id="messages" style="display: none;">
      {% for message in messages %}
        <li{% if message.tags %}
          data-message-type="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
  {% endif %}

    <div class="m-b-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">Printery</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'articles:article_list' %}">{% trans "Articles" %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'articles:user_article_list' %}">{% trans "My Articles" %}</a>
              </li>
                  <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% block content %}
        <p>
          We are so sorry, this page is under development. Our team make all possible to bring it to live as soon as possible. While you can check other available pages.
        </p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->

      <script src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}
  </body>
</html>